// packages/angular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { Subject } from 'rxjs';

import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  form$ = new Subject();

  loginForm;

  constructor(private authService: AuthService, private formBuilder: FormBuilder) {
    this.loginForm = this.formBuilder.group({
      email: '',
      password: '',
    });

    this.authService.loginUser(this.form$).subscribe(response => {
      console.log(response);
      this.loginForm.reset();
    });
  }
}

<main class="login__wrapper">
  <form class="form__wrapper" [formGroup]="loginForm" (ngSubmit)="form$.next(loginForm.value)">
    <label>
      Email:
      <input formControlName="email" id="email" nz-input type="email" />
    </label>
    <label>
      Password:
      <input formControlName="password" id="password" nz-input type="password" />
    </label>
    <button nz-button type="submit" [nzType]="'primary'">Login</button>
  </form>
</main>

// packages/vue/src/views/login.vue
<template>
  <Layout>
    <main class="login__wrapper">
      <form class="form__wrapper" @submit="handleSubmit">
        <label>
          Email:
          <a-input id="email" type="email" v-model="formValues.email" />
        </label>
        <label>
          Password:
          <a-input id="password" type="password" v-model="formValues.password" />
        </label>
        <a-button htmlType="submit" type="primary">Login</a-button>
      </form>
    </main>
  </Layout>
</template>

<script lang="ts">
import { Subject } from 'rxjs';

import Layout from '../components/layout.vue';
import { AuthService } from '../services/auth';

const authService = new AuthService();
const form$ = new Subject<any>();

export default {
  components: {
    Layout,
  },
  data() {
    return {
      formValues: {
        email: '',
        password: '',
      },
    };
  },
  created() {
    authService.loginUser(form$).subscribe(response => {
      console.log(response);
    });
  },
  methods: {
    handleSubmit(e) {
      form$.next(this.formValues);
      e.preventDefault();
    },
  },
};
</script>

<style scoped>
.login__wrapper {
  align-items: center;
  display: flex;
  justify-content: center;
  min-height: 100vh;
}

.form__wrapper {
  background-color: #fff;
  display: grid;
  padding: 32px;
  row-gap: 16px;
}
</style>
