// packages/preact/src/routes/movies.tsx
import styled from '@emotion/styled/macro';
import { Card } from 'antd';
import { html } from 'htm/preact';
import { useEffect, useState } from 'preact/hooks';

import * as tmdbApi from '../api/tmdb';
import { Layout } from '../components/mod';

const MoviesWrapper = styled.main`
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(4, 1fr);
  margin: 16px;
`;

const MoviesPage = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    const subscription = tmdbApi.readMovies$().subscribe(setMovies);

    return () => {
      subscription.unsubscribe();
    };
  }, []);

  return html`
    <${Layout}>
      <${MoviesWrapper}>
        ${movies.map(
          ({ id, overview, poster_path, title }) =>
            html`
              <${Card}
                cover=${html`
                  <img alt=${title} src="https://image.tmdb.org/t/p/w500/${poster_path}" />
                `}
                key="card-${id}"
              >
                <${Card.Meta} description=${overview} title=${title} />
              <//>
            `
        )}
      <//>
    <//>
  `;
};

export default MoviesPage;

// packages/vue/src/views/movies.vue
<template>
  <Layout>
    <main class="movies__wrapper">
      <a-card v-bind:key="'card-'+movie.id" v-for="movie in movies">
        <img
          :alt="movie.title"
          :src="'https://image.tmdb.org/t/p/w500/'+movie.poster_path"
          slot="cover"
        />
        <a-card-meta :title="movie.title">
          <template slot="description">{{movie.overview}}</template>
        </a-card-meta>
      </a-card>
    </main>
  </Layout>
</template>

<script>
import Layout from '../components/layout.vue';
import { TMDbService } from '../services/tmdb';

const tmdbService = new TMDbService();

export default {
  components: {
    Layout,
  },
  data() {
    return {
      movies: [],
    };
  },
  mounted() {
    tmdbService.getMovies().subscribe(result => {
      this.movies = result;
    });
  },
};
</script>

<style scoped>
.movies__wrapper {
  display: grid;
  gap: 16px;
  margin: 16px;
}

@media screen and (min-width: 576px) {
}

@media screen and (min-width: 768px) {
  .movies__wrapper {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media screen and (min-width: 992px) {
}

@media screen and (min-width: 1200px) {
  .movies__wrapper {
    grid-template-columns: repeat(4, 1fr);
  }
}
</style>
