// packages/angular/src/app/search/search.component.ts
import { Component } from '@angular/core';
import { Subject } from 'rxjs';

import { UsersService } from '../services/users.service';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
})
export class SearchComponent {
  input$ = new Subject<string>();

  options = [];

  constructor(private usersService: UsersService) {
    this.usersService.searchUsers(this.input$).subscribe(users => {
      this.options = users;
    });
  }
}

<app-layout>
  <input nz-input (input)="input$.next($event.currentTarget.value)" [nzAutocomplete]="search" />
  <nz-autocomplete #search>
    <nz-auto-option *ngFor="let option of options">
      {{ option.login }}
    </nz-auto-option>
  </nz-autocomplete>
</app-layout>

// packages/vue/src/views/search.vue
<template>
  <layout>
    <a-auto-complete @search="handleInputChange">
      <template slot="dataSource">
        <a-select-option v-for="option in options" :key="option.node_id">{{option.login}}</a-select-option>
      </template>
    </a-auto-complete>
  </layout>
</template>

<script lang="ts">
import { Subject } from 'rxjs';

import Layout from '../components/layout.vue';
import { UsersService } from '../services/users';

const usersService = new UsersService();
const input$ = new Subject<string>();

export default {
  components: {
    Layout,
  },
  data() {
    return {
      options: [],
    };
  },
  created() {
    // search users by input keyword
    usersService.searchUsers(input$).subscribe(users => {
      this.options = users;
    });
  },
  methods: {
    handleInputChange(value) {
      input$.next(value);
    },
  },
};
</script>
